// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn3LZ7UD7-UoGHJagYfxyFb4u_yRs5X7Y',
    appId: '1:1065046409502:web:5e81817af78e7c2865890f',
    messagingSenderId: '1065046409502',
    projectId: 'vitalbmi-xi',
    authDomain: 'vitalbmi-xi.firebaseapp.com',
    storageBucket: 'vitalbmi-xi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAteithcCpQVgeEx6DQFpkuHZxn8W-DoRc',
    appId: '1:1065046409502:android:9382976eb86055a465890f',
    messagingSenderId: '1065046409502',
    projectId: 'vitalbmi-xi',
    storageBucket: 'vitalbmi-xi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ69UdULzNp6x9v9YCWbMrGyqmeoiUykc',
    appId: '1:1065046409502:ios:4060640bcea6b66665890f',
    messagingSenderId: '1065046409502',
    projectId: 'vitalbmi-xi',
    storageBucket: 'vitalbmi-xi.firebasestorage.app',
    iosBundleId: 'com.example.vitalBmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ69UdULzNp6x9v9YCWbMrGyqmeoiUykc',
    appId: '1:1065046409502:ios:4060640bcea6b66665890f',
    messagingSenderId: '1065046409502',
    projectId: 'vitalbmi-xi',
    storageBucket: 'vitalbmi-xi.firebasestorage.app',
    iosBundleId: 'com.example.vitalBmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn3LZ7UD7-UoGHJagYfxyFb4u_yRs5X7Y',
    appId: '1:1065046409502:web:fa19662a3b77b3ef65890f',
    messagingSenderId: '1065046409502',
    projectId: 'vitalbmi-xi',
    authDomain: 'vitalbmi-xi.firebaseapp.com',
    storageBucket: 'vitalbmi-xi.firebasestorage.app',
  );
}
